// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('User', {
      email: {
        type: DataTypes.STRING,
        validate: {
          isEmail: true
        }
      },
      name: DataTypes.STRING,
      salt: DataTypes.STRING,
      password: DataTypes.STRING
    });
  };

}).call(this);
