// Generated by CoffeeScript 1.3.3
(function() {
  var User;

  require('../lib/db');

  User = db.define("person", {
    "email": {
      "type": "string"
    },
    "salt": {
      "type": "string"
    },
    "password": {
      "type": "string"
    }
  });

}).call(this);
