// Generated by CoffeeScript 1.3.3
(function() {
  var app, express, fs, jade, port;

  fs = require("fs");

  express = require("express");

  jade = require("jade");

  app = express.createServer();

  app.set("view options", {
    layout: false
  });

  app.use(express.bodyParser());

  app.use(express.cookieParser());

  app.use(express.session({
    secret: "94fjf49o843a8"
  }));

  app.use(app.router);

  app.use(express["static"](__dirname + "/../public"));

  app.use(express.errorHandler());

  app.get("/*", function(req, res, next) {
    return next();
  });

  app.get("/", function(req, res) {
    return res.render("index.jade");
  });

  app.get('/logout', function(req, res) {
    req.logout();
    return res.redirect('/');
  });

  app.dynamicHelpers({
    session: function(req, res) {
      return req.session;
    }
  });

  port = process.env.port || 10000;

  app.listen(port);

  console.log("Serving on port " + port);

}).call(this);
