// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    hostname: "http://dev.winterparkelkcourtescapes.com:10000",
    mongo: {
      host: "dev.winterparkelkcourtescapes.com",
      database: "wpece"
    },
    facebook: {
      appId: '373043746094559',
      appSecret: 'c8006f02927e3377bcaab056893e9f91'
    },
    google: {
      appId: '502668132702.apps.googleusercontent.com',
      appSecret: 'unwhekGfKsiqcx0yxu7iA8tY'
    }
  };

}).call(this);
