// Generated by CoffeeScript 1.3.3
(function() {
  var config;

  config = {};

  config.mysql = {};

  config.mysql.host = "localhost";

  config.mysql.port = 3306;

  config.mysql.user = "wpece";

  config.mysql.password = "secret";

  config.mysql.database = "wpece";

  module.exports = config;

}).call(this);
