// Generated by CoffeeScript 1.3.3
(function() {

  $(document).ready(function() {
    var $login;
    $login = $('#login');
    return $('#login_button').click(function() {
      console.log('login');
      $login.css('left', Math.max(($(window).width() - $login.width()) / 2, 0));
      return $login.show();
    });
  });

}).call(this);
