// Generated by CoffeeScript 1.3.3
(function() {
  var _this = this;

  ({
    show_signedin: function(user_email) {
      $('#signedout').hide();
      $('#signedin').show();
      return $('#signed_in_as').text("Signed in as " + user_email);
    },
    check_signedin: function() {
      return false;
    }
  });

  $(document).ready(function() {
    var $signin, $signin_form;
    $signin = $('#signin');
    $('#signin_button').click(function() {
      $signin.css('left', Math.max(($(window).width() - $signin.width()) / 2, 0));
      return $signin.show();
    });
    $signin_form = $('#signin_form');
    return $signin_form.submit(function() {
      var data;
      data = $signin_form.serialize();
      return $.post('/signin', data).done(function(received) {
        console.log("signin success");
        $signin.hide();
        return show_signedin(data.email);
      }).error(function(jqXHR, textStatus) {
        return console.log("signin failed: " + textStatus);
      });
    });
  });

}).call(this);
