// Generated by CoffeeScript 1.3.3
(function() {

  $(document).ready(function() {
    var $login, $signup;
    $login = $('#login');
    $signup = $('#signup');
    $('#login_button').click(function() {
      $login.css('left', Math.max(($(window).width() - $login.width()) / 2, 0));
      return $login.show();
    });
    $('#signup_button').click(function() {
      $signup.css('left', Math.max(($(window).width() - $signup.width()) / 2, 0));
      return $signup.show();
    });
    $('#login_close').click(function() {
      return $login.hide();
    });
    return $('#signup_close').click(function() {
      return $signup.hide();
    });
  });

}).call(this);
