// Generated by CoffeeScript 1.3.3
(function() {
  var slideshow_init;

  slideshow_init = function() {
    var $slideshow, displayTimeSeconds, fadeTimeSeconds, h, w;
    fadeTimeSeconds = 1;
    displayTimeSeconds = 4;
    $slideshow = $('#slideshow');
    w = $slideshow.width();
    h = $slideshow.height();
    $.each($('#slideshow img'), function(i, im) {
      return im.onload = function() {
        return this.width /= Math.max(this.width / w, this.height / h);
      };
    });
    $("#slideshow > div:gt(0)").hide();
    return setInterval(function() {
      return $('#slideshow > div:first').fadeOut(1000 * fadeTimeSeconds).next().fadeIn(1000 * fadeTimeSeconds).end().appendTo('#slideshow');
    }, 1000 * displayTimeSeconds);
  };

  $(document).ready(function() {
    return slideshow_init();
  });

}).call(this);
